-- 0008 · Datos de referencia: municipios y barrios de la Región de Murcia.
-- ARCHIVO GENERADO por `npm run zonas:sql` desde src/zonas/datos.ts. No editar a mano.
-- Centroides y colindancias APROXIMADOS hasta cargar las geometrías del CNIG (docs/DECISIONES.md, D-111).

insert into public.zones (level, path, slug, name, aliases, ine_code, centroid)
select 'municipio', v.path, v.slug, v.name, v.aliases, v.ine, v.centroid
from (values
  ('abanilla', 'abanilla', 'Abanilla', '{}'::text[], '30001', extensions.st_setsrid(extensions.st_makepoint(-1.041, 38.206), 4326)::extensions.geography),
  ('abaran', 'abaran', 'Abarán', '{}'::text[], '30002', extensions.st_setsrid(extensions.st_makepoint(-1.4, 38.204), 4326)::extensions.geography),
  ('aguilas', 'aguilas', 'Águilas', '{}'::text[], '30003', extensions.st_setsrid(extensions.st_makepoint(-1.5829, 37.4063), 4326)::extensions.geography),
  ('albudeite', 'albudeite', 'Albudeite', '{}'::text[], '30004', extensions.st_setsrid(extensions.st_makepoint(-1.386, 38.029), 4326)::extensions.geography),
  ('alcantarilla', 'alcantarilla', 'Alcantarilla', '{}'::text[], '30005', extensions.st_setsrid(extensions.st_makepoint(-1.217, 37.9694), 4326)::extensions.geography),
  ('aledo', 'aledo', 'Aledo', '{}'::text[], '30006', extensions.st_setsrid(extensions.st_makepoint(-1.573, 37.796), 4326)::extensions.geography),
  ('alguazas', 'alguazas', 'Alguazas', '{}'::text[], '30007', extensions.st_setsrid(extensions.st_makepoint(-1.242, 38.052), 4326)::extensions.geography),
  ('alhama-de-murcia', 'alhama-de-murcia', 'Alhama de Murcia', array['alhama']::text[], '30008', extensions.st_setsrid(extensions.st_makepoint(-1.4253, 37.8519), 4326)::extensions.geography),
  ('archena', 'archena', 'Archena', '{}'::text[], '30009', extensions.st_setsrid(extensions.st_makepoint(-1.3, 38.116), 4326)::extensions.geography),
  ('beniel', 'beniel', 'Beniel', '{}'::text[], '30010', extensions.st_setsrid(extensions.st_makepoint(-1.001, 38.046), 4326)::extensions.geography),
  ('blanca', 'blanca', 'Blanca', '{}'::text[], '30011', extensions.st_setsrid(extensions.st_makepoint(-1.374, 38.179), 4326)::extensions.geography),
  ('bullas', 'bullas', 'Bullas', '{}'::text[], '30012', extensions.st_setsrid(extensions.st_makepoint(-1.67, 38.046), 4326)::extensions.geography),
  ('calasparra', 'calasparra', 'Calasparra', '{}'::text[], '30013', extensions.st_setsrid(extensions.st_makepoint(-1.699, 38.23), 4326)::extensions.geography),
  ('campos-del-rio', 'campos-del-rio', 'Campos del Río', '{}'::text[], '30014', extensions.st_setsrid(extensions.st_makepoint(-1.355, 38.039), 4326)::extensions.geography),
  ('caravaca-de-la-cruz', 'caravaca-de-la-cruz', 'Caravaca de la Cruz', array['caravaca']::text[], '30015', extensions.st_setsrid(extensions.st_makepoint(-1.862, 38.106), 4326)::extensions.geography),
  ('cartagena', 'cartagena', 'Cartagena', array['cartajena', 'ctg']::text[], '30016', extensions.st_setsrid(extensions.st_makepoint(-0.9966, 37.6257), 4326)::extensions.geography),
  ('cehegin', 'cehegin', 'Cehegín', '{}'::text[], '30017', extensions.st_setsrid(extensions.st_makepoint(-1.799, 38.092), 4326)::extensions.geography),
  ('ceuti', 'ceuti', 'Ceutí', '{}'::text[], '30018', extensions.st_setsrid(extensions.st_makepoint(-1.273, 38.079), 4326)::extensions.geography),
  ('cieza', 'cieza', 'Cieza', '{}'::text[], '30019', extensions.st_setsrid(extensions.st_makepoint(-1.4189, 38.2394), 4326)::extensions.geography),
  ('fortuna', 'fortuna', 'Fortuna', '{}'::text[], '30020', extensions.st_setsrid(extensions.st_makepoint(-1.125, 38.181), 4326)::extensions.geography),
  ('fuente-alamo-de-murcia', 'fuente-alamo-de-murcia', 'Fuente Álamo de Murcia', array['fuente alamo']::text[], '30021', extensions.st_setsrid(extensions.st_makepoint(-1.169, 37.723), 4326)::extensions.geography),
  ('jumilla', 'jumilla', 'Jumilla', '{}'::text[], '30022', extensions.st_setsrid(extensions.st_makepoint(-1.329, 38.475), 4326)::extensions.geography),
  ('librilla', 'librilla', 'Librilla', '{}'::text[], '30023', extensions.st_setsrid(extensions.st_makepoint(-1.356, 37.887), 4326)::extensions.geography),
  ('lorca', 'lorca', 'Lorca', '{}'::text[], '30024', extensions.st_setsrid(extensions.st_makepoint(-1.7003, 37.6771), 4326)::extensions.geography),
  ('lorqui', 'lorqui', 'Lorquí', '{}'::text[], '30025', extensions.st_setsrid(extensions.st_makepoint(-1.251, 38.082), 4326)::extensions.geography),
  ('mazarron', 'mazarron', 'Mazarrón', array['mazaron']::text[], '30026', extensions.st_setsrid(extensions.st_makepoint(-1.3149, 37.599), 4326)::extensions.geography),
  ('molina-de-segura', 'molina-de-segura', 'Molina de Segura', array['molina']::text[], '30027', extensions.st_setsrid(extensions.st_makepoint(-1.2076, 38.0546), 4326)::extensions.geography),
  ('moratalla', 'moratalla', 'Moratalla', '{}'::text[], '30028', extensions.st_setsrid(extensions.st_makepoint(-1.891, 38.189), 4326)::extensions.geography),
  ('mula', 'mula', 'Mula', '{}'::text[], '30029', extensions.st_setsrid(extensions.st_makepoint(-1.49, 38.042), 4326)::extensions.geography),
  ('murcia', 'murcia', 'Murcia', array['murcia capital', 'murcia ciudad']::text[], '30030', extensions.st_setsrid(extensions.st_makepoint(-1.1307, 37.9922), 4326)::extensions.geography),
  ('ojos', 'ojos', 'Ojós', '{}'::text[], '30031', extensions.st_setsrid(extensions.st_makepoint(-1.344, 38.148), 4326)::extensions.geography),
  ('pliego', 'pliego', 'Pliego', '{}'::text[], '30032', extensions.st_setsrid(extensions.st_makepoint(-1.501, 37.99), 4326)::extensions.geography),
  ('puerto-lumbreras', 'puerto-lumbreras', 'Puerto Lumbreras', '{}'::text[], '30033', extensions.st_setsrid(extensions.st_makepoint(-1.809, 37.563), 4326)::extensions.geography),
  ('ricote', 'ricote', 'Ricote', '{}'::text[], '30034', extensions.st_setsrid(extensions.st_makepoint(-1.365, 38.153), 4326)::extensions.geography),
  ('san-javier', 'san-javier', 'San Javier', '{}'::text[], '30035', extensions.st_setsrid(extensions.st_makepoint(-0.8375, 37.8063), 4326)::extensions.geography),
  ('san-pedro-del-pinatar', 'san-pedro-del-pinatar', 'San Pedro del Pinatar', array['san pedro', 'pinatar']::text[], '30036', extensions.st_setsrid(extensions.st_makepoint(-0.791, 37.835), 4326)::extensions.geography),
  ('torre-pacheco', 'torre-pacheco', 'Torre-Pacheco', array['torre pacheco', 'pacheco']::text[], '30037', extensions.st_setsrid(extensions.st_makepoint(-0.9533, 37.7431), 4326)::extensions.geography),
  ('las-torres-de-cotillas', 'las-torres-de-cotillas', 'Las Torres de Cotillas', array['torres de cotillas']::text[], '30038', extensions.st_setsrid(extensions.st_makepoint(-1.241, 38.028), 4326)::extensions.geography),
  ('totana', 'totana', 'Totana', '{}'::text[], '30039', extensions.st_setsrid(extensions.st_makepoint(-1.5003, 37.7689), 4326)::extensions.geography),
  ('ulea', 'ulea', 'Ulea', '{}'::text[], '30040', extensions.st_setsrid(extensions.st_makepoint(-1.329, 38.141), 4326)::extensions.geography),
  ('la-union', 'la-union', 'La Unión', array['la union']::text[], '30041', extensions.st_setsrid(extensions.st_makepoint(-0.877, 37.619), 4326)::extensions.geography),
  ('villanueva-del-rio-segura', 'villanueva-del-rio-segura', 'Villanueva del Río Segura', array['villanueva del segura']::text[], '30042', extensions.st_setsrid(extensions.st_makepoint(-1.323, 38.136), 4326)::extensions.geography),
  ('yecla', 'yecla', 'Yecla', '{}'::text[], '30043', extensions.st_setsrid(extensions.st_makepoint(-1.115, 38.6135), 4326)::extensions.geography),
  ('santomera', 'santomera', 'Santomera', '{}'::text[], '30044', extensions.st_setsrid(extensions.st_makepoint(-1.049, 38.061), 4326)::extensions.geography),
  ('los-alcazares', 'los-alcazares', 'Los Alcázares', array['alcazares']::text[], '30045', extensions.st_setsrid(extensions.st_makepoint(-0.8505, 37.7442), 4326)::extensions.geography)
) as v(path, slug, name, aliases, ine, centroid)
on conflict (path) do update set name = excluded.name, aliases = excluded.aliases, ine_code = excluded.ine_code, centroid = excluded.centroid;

insert into public.zones (level, parent_id, path, slug, name, aliases, centroid)
select 'barrio', p.id, v.path, v.slug, v.name, v.aliases, v.centroid
from (values
  ('murcia', 'murcia/centro', 'centro', 'Centro', array['casco antiguo', 'centro historico', 'catedral', 'santa catalina', 'san bartolome', 'san nicolas', 'san pedro murcia', 'plaza circular', 'gran via']::text[], extensions.st_setsrid(extensions.st_makepoint(-1.1285, 37.984), 4326)::extensions.geography),
  ('murcia', 'murcia/el-carmen', 'el-carmen', 'El Carmen', array['barrio del carmen', 'carmen']::text[], extensions.st_setsrid(extensions.st_makepoint(-1.13, 37.978), 4326)::extensions.geography),
  ('murcia', 'murcia/la-flota', 'la-flota', 'La Flota', array['flota']::text[], extensions.st_setsrid(extensions.st_makepoint(-1.126, 37.9985), 4326)::extensions.geography),
  ('murcia', 'murcia/vistalegre', 'vistalegre', 'Vistalegre', array['vista alegre']::text[], extensions.st_setsrid(extensions.st_makepoint(-1.119, 38), 4326)::extensions.geography),
  ('murcia', 'murcia/santa-maria-de-gracia', 'santa-maria-de-gracia', 'Santa María de Gracia', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.137, 37.997), 4326)::extensions.geography),
  ('murcia', 'murcia/el-ranero', 'el-ranero', 'El Ranero', array['ranero']::text[], extensions.st_setsrid(extensions.st_makepoint(-1.137, 38.005), 4326)::extensions.geography),
  ('murcia', 'murcia/juan-carlos-i', 'juan-carlos-i', 'Juan Carlos I', array['zona norte', 'juan carlos primero']::text[], extensions.st_setsrid(extensions.st_makepoint(-1.127, 38.01), 4326)::extensions.geography),
  ('murcia', 'murcia/infante-juan-manuel', 'infante-juan-manuel', 'Infante Juan Manuel', array['infante']::text[], extensions.st_setsrid(extensions.st_makepoint(-1.125, 37.975), 4326)::extensions.geography),
  ('murcia', 'murcia/santiago-el-mayor', 'santiago-el-mayor', 'Santiago el Mayor', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.14, 37.976), 4326)::extensions.geography),
  ('murcia', 'murcia/espinardo', 'espinardo', 'Espinardo', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.157, 38.011), 4326)::extensions.geography),
  ('murcia', 'murcia/el-palmar', 'el-palmar', 'El Palmar', array['palmar']::text[], extensions.st_setsrid(extensions.st_makepoint(-1.16, 37.938), 4326)::extensions.geography),
  ('murcia', 'murcia/la-alberca', 'la-alberca', 'La Alberca', array['alberca']::text[], extensions.st_setsrid(extensions.st_makepoint(-1.133, 37.94), 4326)::extensions.geography),
  ('murcia', 'murcia/churra', 'churra', 'Churra', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.145, 38.025), 4326)::extensions.geography),
  ('murcia', 'murcia/cabezo-de-torres', 'cabezo-de-torres', 'Cabezo de Torres', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.119, 38.029), 4326)::extensions.geography),
  ('murcia', 'murcia/puente-tocinos', 'puente-tocinos', 'Puente Tocinos', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.096, 37.987), 4326)::extensions.geography),
  ('murcia', 'murcia/guadalupe', 'guadalupe', 'Guadalupe', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.165, 38.002), 4326)::extensions.geography),
  ('murcia', 'murcia/beniajan', 'beniajan', 'Beniaján', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.066, 37.979), 4326)::extensions.geography),
  ('murcia', 'murcia/algezares', 'algezares', 'Algezares', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.111, 37.951), 4326)::extensions.geography),
  ('murcia', 'murcia/sangonera-la-verde', 'sangonera-la-verde', 'Sangonera la Verde', array['sangonera']::text[], extensions.st_setsrid(extensions.st_makepoint(-1.201, 37.936), 4326)::extensions.geography),
  ('murcia', 'murcia/torreaguera', 'torreaguera', 'Torreagüera', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.055, 37.979), 4326)::extensions.geography),
  ('cartagena', 'cartagena/casco-antiguo', 'casco-antiguo', 'Casco Antiguo', array['centro', 'casco historico']::text[], extensions.st_setsrid(extensions.st_makepoint(-0.984, 37.599), 4326)::extensions.geography),
  ('cartagena', 'cartagena/ensanche', 'ensanche', 'Ensanche', array['ensanche almarjal', 'almarjal']::text[], extensions.st_setsrid(extensions.st_makepoint(-0.98, 37.609), 4326)::extensions.geography),
  ('cartagena', 'cartagena/barrio-peral', 'barrio-peral', 'Barrio Peral', array['peral']::text[], extensions.st_setsrid(extensions.st_makepoint(-0.992, 37.616), 4326)::extensions.geography),
  ('cartagena', 'cartagena/san-anton', 'san-anton', 'San Antón', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-0.974, 37.613), 4326)::extensions.geography),
  ('cartagena', 'cartagena/los-dolores', 'los-dolores', 'Los Dolores', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-0.993, 37.625), 4326)::extensions.geography),
  ('cartagena', 'cartagena/santa-lucia', 'santa-lucia', 'Santa Lucía', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-0.971, 37.597), 4326)::extensions.geography),
  ('cartagena', 'cartagena/cabo-de-palos', 'cabo-de-palos', 'Cabo de Palos', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-0.693, 37.632), 4326)::extensions.geography),
  ('cartagena', 'cartagena/la-manga', 'la-manga', 'La Manga (Cartagena)', array['la manga', 'la manga del mar menor', 'manga']::text[], extensions.st_setsrid(extensions.st_makepoint(-0.715, 37.64), 4326)::extensions.geography),
  ('cartagena', 'cartagena/playa-honda', 'playa-honda', 'Playa Honda', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-0.755, 37.639), 4326)::extensions.geography),
  ('cartagena', 'cartagena/mar-de-cristal', 'mar-de-cristal', 'Mar de Cristal', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-0.747, 37.65), 4326)::extensions.geography),
  ('cartagena', 'cartagena/los-belones', 'los-belones', 'Los Belones', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-0.776, 37.62), 4326)::extensions.geography),
  ('cartagena', 'cartagena/los-urrutias', 'los-urrutias', 'Los Urrutias', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-0.833, 37.677), 4326)::extensions.geography),
  ('cartagena', 'cartagena/los-nietos', 'los-nietos', 'Los Nietos', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-0.793, 37.651), 4326)::extensions.geography),
  ('cartagena', 'cartagena/islas-menores', 'islas-menores', 'Islas Menores', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-0.803, 37.645), 4326)::extensions.geography),
  ('cartagena', 'cartagena/el-algar', 'el-algar', 'El Algar', array['algar']::text[], extensions.st_setsrid(extensions.st_makepoint(-0.871, 37.649), 4326)::extensions.geography),
  ('cartagena', 'cartagena/pozo-estrecho', 'pozo-estrecho', 'Pozo Estrecho', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-0.995, 37.705), 4326)::extensions.geography),
  ('cartagena', 'cartagena/la-aljorra', 'la-aljorra', 'La Aljorra', array['aljorra']::text[], extensions.st_setsrid(extensions.st_makepoint(-1.062, 37.689), 4326)::extensions.geography),
  ('cartagena', 'cartagena/isla-plana', 'isla-plana', 'Isla Plana', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.192, 37.578), 4326)::extensions.geography),
  ('cartagena', 'cartagena/canteras', 'canteras', 'Canteras', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.035, 37.613), 4326)::extensions.geography),
  ('san-javier', 'san-javier/centro', 'centro', 'San Javier centro', array['centro']::text[], extensions.st_setsrid(extensions.st_makepoint(-0.8375, 37.8063), 4326)::extensions.geography),
  ('san-javier', 'san-javier/santiago-de-la-ribera', 'santiago-de-la-ribera', 'Santiago de la Ribera', array['la ribera', 'santiago ribera', 'ribera']::text[], extensions.st_setsrid(extensions.st_makepoint(-0.807, 37.797), 4326)::extensions.geography),
  ('san-javier', 'san-javier/la-manga', 'la-manga', 'La Manga (San Javier)', array['la manga', 'la manga del mar menor', 'manga']::text[], extensions.st_setsrid(extensions.st_makepoint(-0.752, 37.72), 4326)::extensions.geography),
  ('san-javier', 'san-javier/el-mirador', 'el-mirador', 'El Mirador', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-0.821, 37.817), 4326)::extensions.geography),
  ('san-javier', 'san-javier/roda', 'roda', 'Roda', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-0.872, 37.803), 4326)::extensions.geography),
  ('san-pedro-del-pinatar', 'san-pedro-del-pinatar/centro', 'centro', 'San Pedro del Pinatar centro', array['centro']::text[], extensions.st_setsrid(extensions.st_makepoint(-0.791, 37.835), 4326)::extensions.geography),
  ('san-pedro-del-pinatar', 'san-pedro-del-pinatar/lo-pagan', 'lo-pagan', 'Lo Pagán', array['lo pagan']::text[], extensions.st_setsrid(extensions.st_makepoint(-0.78, 37.819), 4326)::extensions.geography),
  ('san-pedro-del-pinatar', 'san-pedro-del-pinatar/los-cuarteros', 'los-cuarteros', 'Los Cuarteros', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-0.808, 37.842), 4326)::extensions.geography),
  ('los-alcazares', 'los-alcazares/centro', 'centro', 'Los Alcázares centro', array['centro']::text[], extensions.st_setsrid(extensions.st_makepoint(-0.8505, 37.7442), 4326)::extensions.geography),
  ('los-alcazares', 'los-alcazares/los-narejos', 'los-narejos', 'Los Narejos', array['narejos']::text[], extensions.st_setsrid(extensions.st_makepoint(-0.842, 37.755), 4326)::extensions.geography),
  ('torre-pacheco', 'torre-pacheco/centro', 'centro', 'Torre-Pacheco centro', array['centro']::text[], extensions.st_setsrid(extensions.st_makepoint(-0.9533, 37.7431), 4326)::extensions.geography),
  ('torre-pacheco', 'torre-pacheco/roldan', 'roldan', 'Roldán', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-0.972, 37.771), 4326)::extensions.geography),
  ('torre-pacheco', 'torre-pacheco/balsicas', 'balsicas', 'Balsicas', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-0.954, 37.813), 4326)::extensions.geography),
  ('torre-pacheco', 'torre-pacheco/dolores-de-pacheco', 'dolores-de-pacheco', 'Dolores de Pacheco', array['dolores']::text[], extensions.st_setsrid(extensions.st_makepoint(-0.934, 37.778), 4326)::extensions.geography),
  ('mazarron', 'mazarron/centro', 'centro', 'Mazarrón centro', array['centro', 'mazarron pueblo']::text[], extensions.st_setsrid(extensions.st_makepoint(-1.3149, 37.599), 4326)::extensions.geography),
  ('mazarron', 'mazarron/puerto-de-mazarron', 'puerto-de-mazarron', 'Puerto de Mazarrón', array['el puerto', 'puerto mazarron']::text[], extensions.st_setsrid(extensions.st_makepoint(-1.256, 37.565), 4326)::extensions.geography),
  ('mazarron', 'mazarron/bolnuevo', 'bolnuevo', 'Bolnuevo', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.298, 37.56), 4326)::extensions.geography),
  ('mazarron', 'mazarron/camposol', 'camposol', 'Camposol', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.402, 37.597), 4326)::extensions.geography),
  ('aguilas', 'aguilas/centro', 'centro', 'Águilas centro', array['centro']::text[], extensions.st_setsrid(extensions.st_makepoint(-1.5829, 37.4063), 4326)::extensions.geography),
  ('aguilas', 'aguilas/calabardina', 'calabardina', 'Calabardina', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.53, 37.43), 4326)::extensions.geography),
  ('lorca', 'lorca/centro', 'centro', 'Lorca centro', array['centro']::text[], extensions.st_setsrid(extensions.st_makepoint(-1.7003, 37.6771), 4326)::extensions.geography),
  ('lorca', 'lorca/la-hoya', 'la-hoya', 'La Hoya', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.644, 37.739), 4326)::extensions.geography),
  ('lorca', 'lorca/ramonete', 'ramonete', 'Ramonete', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.499, 37.556), 4326)::extensions.geography),
  ('molina-de-segura', 'molina-de-segura/centro', 'centro', 'Molina de Segura centro', array['centro']::text[], extensions.st_setsrid(extensions.st_makepoint(-1.2076, 38.0546), 4326)::extensions.geography),
  ('molina-de-segura', 'molina-de-segura/altorreal', 'altorreal', 'Altorreal', '{}'::text[], extensions.st_setsrid(extensions.st_makepoint(-1.229, 38.085), 4326)::extensions.geography),
  ('molina-de-segura', 'molina-de-segura/la-alcayna', 'la-alcayna', 'La Alcayna', array['alcayna']::text[], extensions.st_setsrid(extensions.st_makepoint(-1.241, 38.088), 4326)::extensions.geography)
) as v(parent_path, path, slug, name, aliases, centroid)
join public.zones p on p.path = v.parent_path
on conflict (path) do update set parent_id = excluded.parent_id, name = excluded.name, aliases = excluded.aliases, centroid = excluded.centroid;

insert into public.zone_adjacency (zone_id, neighbor_id)
select a.id, b.id
from (values
  ('abanilla', 'jumilla'),
  ('abanilla', 'molina-de-segura'),
  ('abanilla', 'santomera'),
  ('abaran', 'blanca'),
  ('abaran', 'cieza'),
  ('aguilas', 'lorca'),
  ('aguilas', 'puerto-lumbreras'),
  ('albudeite', 'campos-del-rio'),
  ('albudeite', 'mula'),
  ('alcantarilla', 'las-torres-de-cotillas'),
  ('alcantarilla', 'murcia'),
  ('aledo', 'lorca'),
  ('aledo', 'totana'),
  ('alguazas', 'campos-del-rio'),
  ('alguazas', 'ceuti'),
  ('alguazas', 'las-torres-de-cotillas'),
  ('alguazas', 'molina-de-segura'),
  ('alhama-de-murcia', 'fuente-alamo-de-murcia'),
  ('alhama-de-murcia', 'librilla'),
  ('alhama-de-murcia', 'mula'),
  ('alhama-de-murcia', 'murcia'),
  ('alhama-de-murcia', 'totana'),
  ('archena', 'blanca'),
  ('archena', 'ceuti'),
  ('archena', 'fortuna'),
  ('archena', 'lorqui'),
  ('archena', 'molina-de-segura'),
  ('archena', 'ulea'),
  ('archena', 'villanueva-del-rio-segura'),
  ('beniel', 'murcia'),
  ('blanca', 'abaran'),
  ('blanca', 'archena'),
  ('blanca', 'cieza'),
  ('blanca', 'ojos'),
  ('blanca', 'ricote'),
  ('blanca', 'ulea'),
  ('bullas', 'cehegin'),
  ('bullas', 'mula'),
  ('calasparra', 'caravaca-de-la-cruz'),
  ('calasparra', 'cehegin'),
  ('calasparra', 'cieza'),
  ('campos-del-rio', 'albudeite'),
  ('campos-del-rio', 'alguazas'),
  ('campos-del-rio', 'las-torres-de-cotillas'),
  ('campos-del-rio', 'mula'),
  ('caravaca-de-la-cruz', 'calasparra'),
  ('caravaca-de-la-cruz', 'cehegin'),
  ('caravaca-de-la-cruz', 'lorca'),
  ('caravaca-de-la-cruz', 'moratalla'),
  ('cartagena', 'fuente-alamo-de-murcia'),
  ('cartagena', 'la-union'),
  ('cartagena', 'los-alcazares'),
  ('cartagena', 'mazarron'),
  ('cartagena', 'murcia'),
  ('cartagena', 'san-javier'),
  ('cartagena', 'torre-pacheco'),
  ('cehegin', 'bullas'),
  ('cehegin', 'calasparra'),
  ('cehegin', 'caravaca-de-la-cruz'),
  ('cehegin', 'lorca'),
  ('cehegin', 'mula'),
  ('ceuti', 'alguazas'),
  ('ceuti', 'archena'),
  ('ceuti', 'lorqui'),
  ('ceuti', 'molina-de-segura'),
  ('cieza', 'abaran'),
  ('cieza', 'blanca'),
  ('cieza', 'calasparra'),
  ('cieza', 'fortuna'),
  ('cieza', 'jumilla'),
  ('cieza', 'moratalla'),
  ('cieza', 'ricote'),
  ('fortuna', 'archena'),
  ('fortuna', 'cieza'),
  ('fortuna', 'jumilla'),
  ('fortuna', 'molina-de-segura'),
  ('fortuna', 'santomera'),
  ('fuente-alamo-de-murcia', 'alhama-de-murcia'),
  ('fuente-alamo-de-murcia', 'cartagena'),
  ('fuente-alamo-de-murcia', 'mazarron'),
  ('fuente-alamo-de-murcia', 'murcia'),
  ('fuente-alamo-de-murcia', 'torre-pacheco'),
  ('jumilla', 'abanilla'),
  ('jumilla', 'cieza'),
  ('jumilla', 'fortuna'),
  ('jumilla', 'yecla'),
  ('librilla', 'alhama-de-murcia'),
  ('librilla', 'mula'),
  ('librilla', 'murcia'),
  ('lorca', 'aguilas'),
  ('lorca', 'aledo'),
  ('lorca', 'caravaca-de-la-cruz'),
  ('lorca', 'cehegin'),
  ('lorca', 'mazarron'),
  ('lorca', 'mula'),
  ('lorca', 'puerto-lumbreras'),
  ('lorca', 'totana'),
  ('lorqui', 'archena'),
  ('lorqui', 'ceuti'),
  ('lorqui', 'molina-de-segura'),
  ('mazarron', 'cartagena'),
  ('mazarron', 'fuente-alamo-de-murcia'),
  ('mazarron', 'lorca'),
  ('mazarron', 'totana'),
  ('molina-de-segura', 'abanilla'),
  ('molina-de-segura', 'alguazas'),
  ('molina-de-segura', 'archena'),
  ('molina-de-segura', 'ceuti'),
  ('molina-de-segura', 'fortuna'),
  ('molina-de-segura', 'las-torres-de-cotillas'),
  ('molina-de-segura', 'lorqui'),
  ('molina-de-segura', 'murcia'),
  ('moratalla', 'caravaca-de-la-cruz'),
  ('moratalla', 'cieza'),
  ('mula', 'albudeite'),
  ('mula', 'alhama-de-murcia'),
  ('mula', 'bullas'),
  ('mula', 'campos-del-rio'),
  ('mula', 'cehegin'),
  ('mula', 'librilla'),
  ('mula', 'lorca'),
  ('mula', 'pliego'),
  ('mula', 'totana'),
  ('murcia', 'alcantarilla'),
  ('murcia', 'alhama-de-murcia'),
  ('murcia', 'beniel'),
  ('murcia', 'cartagena'),
  ('murcia', 'fuente-alamo-de-murcia'),
  ('murcia', 'las-torres-de-cotillas'),
  ('murcia', 'librilla'),
  ('murcia', 'molina-de-segura'),
  ('murcia', 'san-javier'),
  ('murcia', 'santomera'),
  ('murcia', 'torre-pacheco'),
  ('ojos', 'blanca'),
  ('ojos', 'ricote'),
  ('ojos', 'ulea'),
  ('pliego', 'mula'),
  ('puerto-lumbreras', 'aguilas'),
  ('puerto-lumbreras', 'lorca'),
  ('ricote', 'blanca'),
  ('ricote', 'cieza'),
  ('ricote', 'ojos'),
  ('ricote', 'ulea'),
  ('san-javier', 'cartagena'),
  ('san-javier', 'los-alcazares'),
  ('san-javier', 'murcia'),
  ('san-javier', 'san-pedro-del-pinatar'),
  ('san-javier', 'torre-pacheco'),
  ('san-pedro-del-pinatar', 'san-javier'),
  ('torre-pacheco', 'cartagena'),
  ('torre-pacheco', 'fuente-alamo-de-murcia'),
  ('torre-pacheco', 'la-union'),
  ('torre-pacheco', 'los-alcazares'),
  ('torre-pacheco', 'murcia'),
  ('torre-pacheco', 'san-javier'),
  ('las-torres-de-cotillas', 'alcantarilla'),
  ('las-torres-de-cotillas', 'alguazas'),
  ('las-torres-de-cotillas', 'campos-del-rio'),
  ('las-torres-de-cotillas', 'molina-de-segura'),
  ('las-torres-de-cotillas', 'murcia'),
  ('totana', 'aledo'),
  ('totana', 'alhama-de-murcia'),
  ('totana', 'lorca'),
  ('totana', 'mazarron'),
  ('totana', 'mula'),
  ('ulea', 'archena'),
  ('ulea', 'blanca'),
  ('ulea', 'ojos'),
  ('ulea', 'ricote'),
  ('ulea', 'villanueva-del-rio-segura'),
  ('la-union', 'cartagena'),
  ('la-union', 'torre-pacheco'),
  ('villanueva-del-rio-segura', 'archena'),
  ('villanueva-del-rio-segura', 'ulea'),
  ('yecla', 'jumilla'),
  ('santomera', 'abanilla'),
  ('santomera', 'fortuna'),
  ('santomera', 'murcia'),
  ('los-alcazares', 'cartagena'),
  ('los-alcazares', 'san-javier'),
  ('los-alcazares', 'torre-pacheco')
) as v(a, b)
join public.zones a on a.path = v.a
join public.zones b on b.path = v.b
on conflict do nothing;

-- Con geometrías oficiales cargadas, las colindancias se recalculan a partir de ellas.
create or replace function app.recalcular_colindancias() returns int
language plpgsql security definer
set search_path = ''
as $$
declare n int;
begin
  insert into public.zone_adjacency (zone_id, neighbor_id)
  select a.id, b.id from public.zones a join public.zones b
    on a.id <> b.id and a.level = b.level and a.geom is not null and b.geom is not null
   and extensions.st_touches(a.geom::extensions.geometry, b.geom::extensions.geometry)
  on conflict do nothing;
  get diagnostics n = row_count;
  return n;
end $$;
revoke all on function app.recalcular_colindancias() from public, anon, authenticated;
grant execute on function app.recalcular_colindancias() to service_role;
